kind: Secret
apiVersion: v1
metadata:
  name: {{ .Values.clusterName }}
  annotations:
    avp.kubernetes.io/path: "avp/data/monitoring/dynatrace-operator"
    avp.kubernetes.io/secret-version: "1"
type: Opaque
data:
  apiToken: <apiToken>
  dataIngestToken: <dataIngestToken> 
