kind: Secret
apiVersion: v1
metadata:
  namespace: argocd
  name: secret
  annotations:
    avp.kubernetes.io/path: "secret/data/nginx"
    avp.kubernetes.io/secret-version: "1"
type: Opaque
stringData:
  password: <pass>
